import '../spec.dart';

/// Gradle module wrapping the vendor `.aar`.
///
/// Written against the AGP 9 DSL. Under AGP 9.1 the deprecated forms are
/// rejected at SCRIPT COMPILATION, which fails the module before a single
/// source file is read — so `kotlinOptions` inside `android {}` and
/// `sourceSets.java.srcDir` are both avoided here on purpose. They are also
/// still valid under AGP 8, so this output works on both.
String buildGradleKts(BridgeSpec spec) => _gradle(spec).replaceAll(
      'CONSUME_NOTE',
      spec.isFlutter ? _flutterConsume : _nativeConsume,
    );

const _flutterConsume =
    '''// That is fine for how Flutter consumes it: plugin modules are included as
// Gradle SUBPROJECTS and the app depends on `project(":...")`, a path that
// never runs `bundleDebugAar`. It does mean `flutter build aar` (add-to-app)
// is unsupported for the host app while the .aar is in place. The real fix is
// a Maven coordinate from the vendor.''';

const _nativeConsume =
    '''// Consume this as a Gradle SUBPROJECT: include it in settings.gradle and
// depend on `project(":<module>")` -- that path never runs `bundleDebugAar`.
// Publishing it to a repository needs a Maven coordinate from the vendor
// rather than a local .aar.''';

String _gradle(BridgeSpec spec) => '''
// Generated by binary-sdk-bridge. Safe to edit — it is not regenerated.
//
// The vendor `.aar` is fetched by `tool/fetch_android_sdk.sh` into `libs/` and
// is NOT committed. Its absence must not break the build, so the SDK-backed
// code lives in a source set that is only compiled when the binary is there.
//
// ## Why source sets and not reflection
//
// Kotlin has no `#if`. Reflection would compile without the SDK but throw away
// every compile-time check against the vendor API — precisely the surface
// least worth leaving unchecked. Two source sets keep the real path fully
// type-checked and mirror the iOS `#if ${spec.sdkDefine}` exactly.
plugins {
    id("com.android.library")
    id("org.jetbrains.kotlin.android")
}

val vendorAar = file("libs/${spec.androidAarName}.aar")
val sdkPresent = vendorAar.exists()

android {
    namespace = "${spec.androidPackage}"
    compileSdk = ${spec.androidCompileSdk}

    defaultConfig {
        minSdk = ${spec.androidMinSdk}
    }

    compileOptions {
        sourceCompatibility = JavaVersion.VERSION_${spec.javaVersion}
        targetCompatibility = JavaVersion.VERSION_${spec.javaVersion}
    }

    sourceSets {
        getByName("main") {
            // Exactly one of these is added, and both declare the same
            // `VendorBridge` object — so `main` compiles either way.
            //
            // `directories.add`, not the older `srcDir`: AGP 9.1 rejects the
            // deprecated call at script compilation.
            java.directories.add(
                if (sdkPresent) "src/withSdk/kotlin" else "src/noSdk/kotlin"
            )
        }
    }
}

// AGP 9 form. `kotlinOptions` inside `android {}` binds the script to the
// deprecated extension accessor, which AGP 9.1 rejects at script compilation
// — and drags the `android {}` accessor down with it. This top-level block is
// the sanctioned replacement.
kotlin {
    compilerOptions {
        jvmTarget = org.jetbrains.kotlin.gradle.dsl.JvmTarget.JVM_${spec.javaVersion}
    }
}

// ⚠️ This module cannot be published as a standalone AAR while the vendor
// binary is present. `bundleDebugAar` fails with "Direct local .aar file
// dependencies are not supported when building an AAR" -- AGP refuses because
// those classes would be silently dropped from the published artifact.
//
CONSUME_NOTE
dependencies {
    if (sdkPresent) {
        // `runtimeOnly`, not `implementation`: nothing here needs the vendor
        // classes at COMPILE time when the bridge is a runtime class lookup,
        // and keeping the .aar off the compile classpath is the honest
        // declaration of what is actually required.
        runtimeOnly(files(vendorAar))
        // A bare .aar carries NO transitive dependency metadata. Every SDK the
        // vendor binary expects at runtime has to be declared HERE by hand,
        // and a missing one is a ClassNotFoundException at call time, not a
        // build error. Prefer a Maven coordinate from the vendor if one exists.
    }
}
''';

String stateKotlin(BridgeSpec spec) => '''
package ${spec.androidPackage}

/**
 * What the SDK is doing right now, as one value.
 *
 * Mirrors `${spec.kitName}State` on iOS, down to the map keys — Dart parses one
 * shape for both platforms. There is no `Unknown` case: every path out of the
 * bridge is either [Ready] or [Unavailable] carrying a reason, so an
 * unanswered state can never be mistaken for a working one.
 */
sealed class VendorState {
    data class Ready(val version: String) : VendorState()

    data class Unavailable(val reason: String) : VendorState()

    /** Wire form for the transport that carries this to your app. */
    fun asMap(): Map<String, Any> = when (this) {
        is Ready -> mapOf("available" to true, "version" to version)
        is Unavailable -> mapOf("available" to false, "reason" to reason)
    }
}
''';

/// Compiled when the `.aar` is absent.
String bridgeKotlinNoSdk(BridgeSpec spec) => '''
package ${spec.androidPackage}.sdk

import ${spec.androidPackage}.VendorState

/**
 * No vendor `.aar` in this build.
 *
 * The twin of this file is `src/withSdk/.../VendorBridge.kt`; the two must keep
 * identical signatures or `main` compiles in one configuration and not the
 * other — a break nobody sees until the binary lands.
 */
object VendorBridge {
    fun probe(): VendorState = VendorState.Unavailable("sdk_not_bundled")

    fun initialize(appId: String, testMode: Boolean): VendorState =
        VendorState.Unavailable("sdk_not_bundled")
}
''';

/// Compiled when the `.aar` is present.
String bridgeKotlinWithSdk(BridgeSpec spec) => '''
package ${spec.androidPackage}.sdk

import ${spec.androidPackage}.VendorState

/**
 * The vendor `.aar` is present — this is where the real calls go.
 *
 * TODO: call the vendor SDK here.
 *
 * Keep the return contract exactly as-is: every path must resolve to
 * ready-or-reason. In particular do NOT report [VendorState.Ready] from an init
 * whose callback has not fired.
 *
 * Reminder: if the host app minifies, R8 will strip classes the vendor loads
 * reflectively by name. Those need keep rules, and the symptom of missing them
 * is a silent runtime failure in RELEASE builds only.
 */
object VendorBridge {
    fun probe(): VendorState = VendorState.Unavailable("bridge_not_implemented")

    fun initialize(appId: String, testMode: Boolean): VendorState =
        VendorState.Unavailable("bridge_not_implemented")
}
''';

String pluginKotlin(BridgeSpec spec) => '''
package ${spec.androidPackage}

import ${spec.androidPackage}.sdk.VendorBridge
import io.flutter.embedding.engine.plugins.FlutterPlugin
import io.flutter.plugin.common.MethodCall
import io.flutter.plugin.common.MethodChannel

/**
 * Flutter entry point. Deliberately thin — it forwards to [VendorBridge] and
 * does nothing else.
 */
class ${spec.pluginClassName}Plugin : FlutterPlugin, MethodChannel.MethodCallHandler {

    private var channel: MethodChannel? = null

    override fun onAttachedToEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        channel = MethodChannel(binding.binaryMessenger, CHANNEL_NAME).also {
            it.setMethodCallHandler(this)
        }
    }

    override fun onDetachedFromEngine(binding: FlutterPlugin.FlutterPluginBinding) {
        channel?.setMethodCallHandler(null)
        channel = null
    }

    override fun onMethodCall(call: MethodCall, result: MethodChannel.Result) {
        when (call.method) {
            "probe" -> result.success(VendorBridge.probe().asMap())

            "initialize" -> {
                val appId = call.argument<String>("appId")
                if (appId.isNullOrEmpty()) {
                    // A missing app ID is a programming error, not a runtime
                    // condition — surfaced as an error rather than folded into
                    // `unavailable`, where it would look like a benign
                    // absent-SDK build and never get fixed.
                    result.error(
                        "invalid_arguments",
                        "initialize requires a non-empty appId",
                        null,
                    )
                    return
                }
                val testMode = call.argument<Boolean>("testMode") ?: false
                result.success(VendorBridge.initialize(appId, testMode).asMap())
            }

            else -> result.notImplemented()
        }
    }

    private companion object {
        /**
         * The `_method` suffix is deliberate: Flutter's binary messenger keys
         * handlers by NAME ALONE, so an EventChannel added later under the bare
         * name would silently overwrite this one's handler.
         */
        const val CHANNEL_NAME = "${spec.channelName}"
    }
}
''';

String androidManifest(BridgeSpec spec) => '''
<manifest xmlns:android="http://schemas.android.com/apk/res/android">
    <!--
      Intentionally empty of permissions.

      A library manifest merges straight into the host app's, so anything
      declared here is silently added to the app. Do not copy permissions out
      of a vendor demo app — declare only what the host app genuinely needs,
      in the host app.
    -->
</manifest>
''';
