import '../spec.dart';

String pubspecYaml(BridgeSpec spec) {
  final platforms = <String>[
    if (spec.hasAndroid)
      '      android:\n'
          '        package: ${spec.androidPackage}\n'
          '        pluginClass: ${spec.pluginClassName}Plugin',
    if (spec.hasIos) '      ios:\n        pluginClass: ${spec.pluginClassName}Plugin',
  ].join('\n');

  return '''
name: ${spec.pluginName}
description: ${spec.description ?? 'Wrapper for a closed-source binary SDK.'}
version: 0.1.0
publish_to: 'none'

environment:
  sdk: ^3.5.0
  flutter: '>=3.24.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
$platforms
''';
}

String stateDart(BridgeSpec spec) => '''
import 'package:flutter/foundation.dart';

/// Whether the vendor SDK is usable in THIS build, as one value.
///
/// Mirrors the native enums. There is no third case on purpose: an absent
/// binary, a stubbed bridge, a failed init and an unregistered plugin all
/// arrive as [VendorState.unavailable] carrying a reason, so the caller has
/// nothing to interpret. Anything that is not explicitly [ready] means off.
@immutable
sealed class VendorState {
  const VendorState();

  const factory VendorState.ready(String version) = VendorReady;

  /// [reason] is a stable machine token from native (`sdk_not_bundled`,
  /// `bridge_not_implemented`, ...) — for logs and debug surfaces, never for
  /// user-facing copy.
  const factory VendorState.unavailable(String reason) = VendorUnavailable;

  bool get isReady => this is VendorReady;

  /// Rebuilds the state from the native channel's map.
  ///
  /// A malformed or null payload resolves to unavailable rather than throwing:
  /// the correct response to a confusing answer is to do nothing, not to
  /// crash the caller.
  factory VendorState.fromMap(Map<Object?, Object?>? map) {
    if (map == null) return const VendorUnavailable('no_response');
    if (map['available'] == true) {
      final version = map['version'];
      return VendorReady(version is String ? version : 'unknown');
    }
    final reason = map['reason'];
    return VendorUnavailable(reason is String ? reason : 'unspecified');
  }
}

final class VendorReady extends VendorState {
  const VendorReady(this.version);

  final String version;

  @override
  bool operator ==(Object other) =>
      other is VendorReady && other.version == version;

  @override
  int get hashCode => Object.hash('ready', version);

  @override
  String toString() => 'VendorState.ready(\$version)';
}

final class VendorUnavailable extends VendorState {
  const VendorUnavailable(this.reason);

  final String reason;

  @override
  bool operator ==(Object other) =>
      other is VendorUnavailable && other.reason == reason;

  @override
  int get hashCode => Object.hash('unavailable', reason);

  @override
  String toString() => 'VendorState.unavailable(\$reason)';
}
''';

String apiDart(BridgeSpec spec) => '''
/// Wrapper for a closed-source binary SDK, generated by binary-sdk-bridge.
library;

import 'package:flutter/foundation.dart';
import 'package:flutter/services.dart';

import 'src/vendor_state.dart';

export 'src/vendor_state.dart';

/// Entry point to the native SDK.
class ${spec.pluginClassName} {
  const ${spec.pluginClassName}._();

  @visibleForTesting
  static const MethodChannel channel = MethodChannel('${spec.channelName}');

  /// Whether the SDK is bundled and wired, without initialising it. Cheap and
  /// side-effect free — useful for a debug surface, and for asserting in a
  /// release smoke test that the binary actually shipped.
  static Future<VendorState> probe() => _invoke('probe');

  /// Initialises the SDK. Safe to call when the binary is absent: the result is
  /// simply [VendorUnavailable].
  static Future<VendorState> initialize({
    required String appId,
    bool testMode = false,
  }) => _invoke('initialize', {'appId': appId, 'testMode': testMode});

  /// One funnel for both calls, so every failure mode — a platform without the
  /// plugin, an older build with no handler, a native throw — lands on the same
  /// answer instead of an exception at the call site.
  static Future<VendorState> _invoke(
    String method, [
    Map<String, Object?>? args,
  ]) async {
    try {
      final result =
          await channel.invokeMapMethod<Object?, Object?>(method, args);
      return VendorState.fromMap(result);
    } on MissingPluginException {
      return const VendorState.unavailable('plugin_not_registered');
    } on PlatformException catch (e) {
      return VendorState.unavailable('platform_error:\${e.code}');
    }
  }
}
''';

String testDart(BridgeSpec spec) => '''
import 'package:flutter/services.dart';
import 'package:flutter_test/flutter_test.dart';
import 'package:${spec.pluginName}/${spec.pluginName}.dart';

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  final messenger =
      TestDefaultBinaryMessengerBinding.instance.defaultBinaryMessenger;

  void mockNative(Future<Object?>? Function(MethodCall call)? handler) {
    messenger.setMockMethodCallHandler(${spec.pluginClassName}.channel, handler);
  }

  tearDown(() => mockNative(null));

  test('a garbage payload is unavailable, never ready', () {
    // The property the whole design rests on: anything that is not an explicit
    // `available: true` must fail closed.
    for (final payload in <Map<Object?, Object?>>[
      <Object?, Object?>{},
      {'available': 'true'},
      {'available': 1},
      {'unexpected': 'shape'},
    ]) {
      expect(VendorState.fromMap(payload).isReady, isFalse,
          reason: 'payload \$payload must not read as ready');
    }
  });

  test('probe forwards the native answer', () async {
    mockNative((call) async => {'available': true, 'version': '1.0.0'});

    expect(await ${spec.pluginClassName}.probe(), const VendorState.ready('1.0.0'));
  });

  test('an unregistered plugin is unavailable, not an exception', () async {
    mockNative(null);

    expect(
      await ${spec.pluginClassName}.probe(),
      const VendorState.unavailable('plugin_not_registered'),
    );
  });
}
''';
