import '../spec.dart';

/// The `Package.swift` that makes the vendor binary optional.
///
/// The probe is the whole point of this project. A `.binaryTarget(path:)`
/// pointing at a file that is not there fails the resolve of the ENTIRE
/// package graph — not just that target — so a checked-out repo without the
/// vendor binary cannot build at all, and CI never can. Probing the filesystem
/// from the manifest and declaring the target conditionally is what keeps the
/// binary genuinely optional.
String packageSwift(BridgeSpec spec) => '''
// swift-tools-version: 5.9
import Foundation
import PackageDescription

// Generated by binary-sdk-bridge. Safe to edit — it is not regenerated.
//
// The vendor binary lives at `Frameworks/${spec.iosFrameworkName}.xcframework`
// and is fetched by `tool/fetch_ios_sdk.sh`. It is deliberately NOT committed.
//
// ## Why the binary is optional
//
// A `.binaryTarget(path:)` whose path does not exist fails the resolve of the
// WHOLE package graph, so without this probe nobody could build the app
// without vendor credentials and CI could never build it at all. Probed here
// instead, an absent binary degrades to a no-op implementation that still
// compiles and still answers Dart.
//
// ⚠️ SPM caches manifest evaluation by manifest CONTENT, not by filesystem
// state. Dropping the binary in afterwards does not by itself flip this
// branch — the fetch script clears the Flutter SPM cache for that reason. In
// Xcode: File ▸ Packages ▸ Reset Package Caches.
let sdkPath = Context.packageDirectory
    + "/Frameworks/${spec.iosFrameworkName}.xcframework"
let sdkPresent = FileManager.default.fileExists(atPath: sdkPath)

var targets: [Target] = []
var kitDependencies: [Target.Dependency] = []
var kitSwiftSettings: [SwiftSetting] = []

if sdkPresent {
    targets.append(
        .binaryTarget(
            name: "${spec.iosFrameworkName}",
            path: "Frameworks/${spec.iosFrameworkName}.xcframework"
        )
    )
    kitDependencies.append("${spec.iosFrameworkName}")
    kitSwiftSettings.append(.define("${spec.sdkDefine}"))
}

// No Flutter import in this target, so a plain iOS app can depend on the
// package directly — and the vendor integration stays unit-testable without
// an engine.
targets.append(
    .target(
        name: "${spec.kitName}",
        dependencies: kitDependencies,
        swiftSettings: kitSwiftSettings
    )
)

targets.append(
    .target(
        name: "${spec.pluginName}",
        dependencies: [
            "${spec.kitName}",
            .product(name: "FlutterFramework", package: "FlutterFramework"),
        ]
    )
)

let package = Package(
    name: "${spec.pluginName}",
    // Keep this in step with the host app's deployment target. Raising it
    // above the app's own is what produces "required a higher minimum
    // deployment target" at link time.
    platforms: [
        .iOS("${spec.iosDeploymentTarget}")
    ],
    products: [
        // The dashed spelling is the convention Flutter's SPM integration
        // looks for — renaming it breaks plugin discovery silently.
        .library(name: "${spec.iosProductName}", targets: ["${spec.pluginName}"]),
        // For a non-Flutter iOS consumer.
        .library(name: "${spec.kitName}", targets: ["${spec.kitName}"]),
    ],
    dependencies: [
        .package(name: "FlutterFramework", path: "../FlutterFramework")
    ],
    targets: targets
)
''';

/// The vendor-facing seam. Everything that knows the SDK exists is behind the
/// compilation condition, so the rest of the app compiles either way.
String bridgeSwift(BridgeSpec spec) => '''
import Foundation

/// What the SDK is doing right now, as one value.
///
/// There is no `unknown` case: every path out of `probe()` and `initialize()`
/// is either `ready` or an `unavailable` carrying a reason. Callers turn the
/// latter straight into "feature off", so an unanswered state can never be
/// mistaken for a working one.
public enum ${spec.kitName}State: Equatable {
    case ready(version: String)
    case unavailable(reason: String)

    /// Wire form for the Flutter method channel. Defined here rather than in
    /// the plugin so the Android side can mirror the same two keys — Dart then
    /// parses one shape for both platforms.
    public var asDictionary: [String: Any] {
        switch self {
        case let .ready(version):
            return ["available": true, "version": version]
        case let .unavailable(reason):
            return ["available": false, "reason": reason]
        }
    }
}

/// The single seam between this app and the vendor SDK.
public enum ${spec.kitName} {

    #if ${spec.sdkDefine}

    // TODO: call the vendor SDK here, against its real headers.
    //
    // Keep the return contract exactly as-is: every path must resolve to
    // ready-or-reason. In particular do NOT report `.ready` from an init whose
    // callback has not fired yet.
    #warning("${spec.kitName}: binary is present but the vendor calls are still stubbed")

    public static func probe() -> ${spec.kitName}State {
        .unavailable(reason: "bridge_not_implemented")
    }

    public static func initialize(appID: String, testMode: Bool) -> ${spec.kitName}State {
        .unavailable(reason: "bridge_not_implemented")
    }

    #else

    /// No vendor binary in this build.
    public static func probe() -> ${spec.kitName}State {
        .unavailable(reason: "sdk_not_bundled")
    }

    public static func initialize(appID: String, testMode: Bool) -> ${spec.kitName}State {
        .unavailable(reason: "sdk_not_bundled")
    }

    #endif
}
''';

String pluginSwift(BridgeSpec spec) => '''
import ${spec.kitName}
import Flutter
import UIKit

/// Flutter entry point. Deliberately thin — it forwards to ${spec.kitName} and
/// does nothing else.
public class ${spec.pluginClassName}Plugin: NSObject, FlutterPlugin {

    /// The `_method` suffix is deliberate: Flutter's binary messenger keys
    /// handlers by NAME ALONE, so an EventChannel added later under the bare
    /// name would silently overwrite this one's handler. Reserving the bare
    /// name now costs nothing.
    private static let channelName = "${spec.channelName}"

    public static func register(with registrar: FlutterPluginRegistrar) {
        let channel = FlutterMethodChannel(
            name: channelName,
            binaryMessenger: registrar.messenger()
        )
        registrar.addMethodCallDelegate(${spec.pluginClassName}Plugin(), channel: channel)
    }

    public func handle(_ call: FlutterMethodCall, result: @escaping FlutterResult) {
        switch call.method {
        case "probe":
            result(${spec.kitName}.probe().asDictionary)

        case "initialize":
            let args = call.arguments as? [String: Any] ?? [:]
            guard let appID = args["appId"] as? String, !appID.isEmpty else {
                // A missing app ID is a programming error, not a runtime
                // condition — surfaced as an error rather than folded into
                // `unavailable`, where it would look like a benign
                // absent-SDK build and never get fixed.
                result(
                    FlutterError(
                        code: "invalid_arguments",
                        message: "initialize requires a non-empty appId",
                        details: nil
                    )
                )
                return
            }
            let testMode = args["testMode"] as? Bool ?? false
            result(${spec.kitName}.initialize(appID: appID, testMode: testMode).asDictionary)

        default:
            result(FlutterMethodNotImplemented)
        }
    }
}
''';
